author = "Themefisher"
blogCategoryType = "category"
contact_form_action = "#"
description = "This is meta description"
image = "images/logoleiste-sibb-accelerator-forderlogos-gesamt-white-background.png"
logo = "images/logo.png"
logo_width = "200px"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = ""
link = ""
title = ""
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-skype"
link = "#"
title = "skype"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
